# Generated by Django 4.2.2 on 2023-06-28 10:43

import app_menu.models.category
import app_menu.models.food
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته', 'verbose_name_plural': 'دسته ها'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'غذا', 'verbose_name_plural': 'غذاها'},
        ),
        migrations.AddField(
            model_name='category',
            name='location',
            field=models.PositiveIntegerField(default=1, verbose_name='جایگاه'),
        ),
        migrations.AddField(
            model_name='food',
            name='location',
            field=models.PositiveIntegerField(default=1, verbose_name='جایگاه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to=app_menu.models.category.category_icon_directory_path, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت فعال بودن'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_foods', to='app_menu.category', verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to=app_menu.models.food.food_image_directory_path, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت فعال بودن'),
        ),
        migrations.AlterField(
            model_name='food',
            name='material',
            field=models.TextField(verbose_name='رسپی'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت'),
        ),
    ]
