# Generated by Django 4.2.2 on 2023-07-15 08:54

import app_menu.models.main_page
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu', '0003_alter_food_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app_menu.models.main_page.main_page_image_directory_path, verbose_name='عکس')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('PHONE', 'Phone Number'), ('ADDRESS', 'Address'), ('INSTAGRAM', 'Instagram'), ('StartTime', 'Start Time'), ('EndTime', 'End Time')], max_length=10, verbose_name='Title')),
                ('value', models.CharField(max_length=100, verbose_name='Value')),
            ],
        ),
    ]
