# Generated by Django 4.2.2 on 2023-09-17 21:32

import app_menu.models.category
import app_menu.models.food
import app_menu.models.main_page
import app_menu.models.settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_menu", "0007_alter_settings_image_alter_settings_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="food",
            options={"verbose_name": "Food", "verbose_name_plural": "Foods"},
        ),
        migrations.AlterModelOptions(
            name="mainpage",
            options={"verbose_name": "Main Page", "verbose_name_plural": "Main Page"},
        ),
        migrations.AlterModelOptions(
            name="settings",
            options={"verbose_name": "Setting", "verbose_name_plural": "Settings"},
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                upload_to=app_menu.models.category.category_icon_directory_path,
                verbose_name="Icon",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="category",
            name="location",
            field=models.PositiveIntegerField(default=1, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="food",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_foods",
                to="app_menu.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=app_menu.models.food.food_image_directory_path,
                verbose_name="تصویر",
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="food",
            name="location",
            field=models.PositiveIntegerField(default=1, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="food",
            name="material",
            field=models.TextField(blank=True, null=True, verbose_name="Material"),
        ),
        migrations.AlterField(
            model_name="food",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="food",
            name="price",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="mainpage",
            name="image",
            field=models.ImageField(
                upload_to=app_menu.models.main_page.main_page_image_directory_path,
                verbose_name="تصویر",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=app_menu.models.settings.setting_image_directory_path,
                verbose_name="تصویر",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="title",
            field=models.CharField(
                choices=[
                    ("PHONE", "Phone Number"),
                    ("ADDRESS", "Address"),
                    ("INSTAGRAM", "Instagram"),
                    ("StartTime", "Start Time"),
                    ("EndTime", "End Time"),
                    ("MenuImage", "Menu Image"),
                ],
                max_length=10,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="value",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Value"
            ),
        ),
    ]
