# Generated by Django 4.2.2 on 2023-09-18 06:50

import app_menu.models.birthday
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_menu", "0008_alter_category_options_alter_food_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Birthday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "price",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "location",
                    models.PositiveIntegerField(default=1, verbose_name="Location"),
                ),
            ],
            options={
                "verbose_name": "Birthday",
                "verbose_name_plural": "Birthdays",
            },
        ),
        migrations.CreateModel(
            name="BirthdayImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_menu.models.birthday.birthday_images_directory_path,
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "birthday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="birthday_images",
                        to="app_menu.birthday",
                        verbose_name="Birthday",
                    ),
                ),
            ],
            options={
                "verbose_name": "Birthday Image",
                "verbose_name_plural": "Birthday Images",
            },
        ),
    ]
